import * as React from 'react'
import Head from 'next/head'
import Header from '@/components/layouts/Header'

const Layout = ({children}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
    </>
  )
}

export default Layout